export const PORT_LIST_REQUEST = 'PORT_LIST_REQUEST';
export const PORT_LIST_SUCCESS = 'PORT_LIST_SUCCESS';
export const PORT_LIST_FAIL = 'PORT_LIST_FAIL';

export const PORT_CONNECT_REQUEST = 'PORT_CONNECT_REQUEST';
export const PORT_CONNECT_SUCCESS = 'PORT_CONNECT_SUCCESS';
export const PORT_CONNECT_FAIL = 'PORT_CONNECT_FAIL';

export const PORT_DISCONNECT_REQUEST = 'PORT_DISCONNECT_REQUEST';
export const PORT_DISCONNECT_SUCCESS = 'PORT_DISCONNECT_SUCCESS';
export const PORT_DISCONNECT_FAIL = 'PORT_DISCONNECT_FAIL';
